site_name: E25-Projekt
logo: images/logo.png  # Optional, path to your logo

theme:
  name: material  # Using the Material theme
  features:
    - navigation.tabs  # Enables top bar navigation with tabs (subpages)
    - toc.inline  # Enables inline table of contents in the sidebar for page navigation

  # TOC settings to ensure it's on the left
  toc:
    position: left  # Ensures the TOC is on the left side of the page

# Define the navigation structure for top bar and subpages (only top-level pages in the sidebar)
nav:
  - Forside: index.md  # This appears in the top bar navigation, not in the sidebar
  - Målsætning: maalsaetning.md  # This appears in the top bar navigation, not in the sidebar

# Optional: Configuration for plugins, like search, markdown extensions, etc.
plugins:
  - search  # Enables search functionality for your site

# Optional: Customizing markdown extensions for syntax highlighting, footnotes, etc.
markdown_extensions:
  - codehilite  # Enables code highlighting for code blocks
  - toc  # Enables table of contents generation (automatically done by the theme too)
